### ISSUE TITLE
get dataset

### ISSUE THREAD

**Issue by ldh032012** [SurajK7/PS-pixels-detection-PSInSAR#3]

**Comment by ldh032012** [comment]
> _No description provided._
Where did the data set used for training come from? please help me， thanks.


>

**Comment by SurajK7** [comment]
Hi there, the dataset used, comprised of differential interferograms from all over San Francisco Bay Area. Hope this answers your query.

**Comment by ldh032012** [comment]
> 



> 



> Hi there, the dataset used, comprised of differential interferograms from all over San Francisc

> Hi there, the dataset used, comprised of differential interferograms from all over San Francisco Bay Area. Hope this answers your query.


> Hi there, the dataset used, comprised of differential interferograms from all over San Francisco Bay Area. Hope this answers your query.

thanks for your answer.Is your dataset public? Or you make it yourself, if you make it yourself what kind of software is used to preprocess it?

**Comment by SurajK7** [comment]
The dataset is not public, but I don't know much about the dataset creation process as it was curated by one of my team members.

**Comment by ldh032012** [comment]
> The dataset is not public, but I don't know much about the dataset creation process as it was curated by one of my team members.

Thanks for you reply,have a good time.

**Comment by ldh032012** [comment]
> The dataset is not public, but I don't know much about the dataset creation process as it was curated by one of my team members.

Can I get the contact information of that person on your team? I'd like to consult him about this

**Comment by ldh032012** [comment]
> The dataset is not public, but I don't know much about the dataset creation process as it was curated by one of my team members.

Here is my email address：472020747ldh@gmail.com

**Comment by SurajK7** [comment]
I have mailed you. Please check.

**Comment by SurajK7** [comment]
I am closing this issue now. Feel free to reopen it if needed.
